import nimlibxlsxwriter/[xlsxwriter, chartsheet]
import nimlibxlsxwriter/common
export common

type
  Workbook*   = ptr lxw_workbook
  Worksheet*  = ptr lxw_worksheet
  Format*     = ptr lxw_format  
  Chartsheet* = ptr lxw_chartsheet 
  Chart*      = ptr lxw_chart 


#[
type
  Error = enum
    errNoError = LXW_NO_ERROR, LXW_ERROR_MEMORY_MALLOC_FAILED, LXW_ERROR_CREATING_XLSX_FILE,
    LXW_ERROR_CREATING_TMPFILE, LXW_ERROR_READING_TMPFILE,
    LXW_ERROR_ZIP_FILE_OPERATION, LXW_ERROR_ZIP_PARAMETER_ERROR,
    LXW_ERROR_ZIP_BAD_ZIP_FILE, LXW_ERROR_ZIP_INTERNAL_ERROR,
    LXW_ERROR_ZIP_FILE_ADD, LXW_ERROR_ZIP_CLOSE, LXW_ERROR_FEATURE_NOT_SUPPORTED,
    LXW_ERROR_NULL_PARAMETER_IGNORED, LXW_ERROR_PARAMETER_VALIDATION,
    LXW_ERROR_SHEETNAME_LENGTH_EXCEEDED, LXW_ERROR_INVALID_SHEETNAME_CHARACTER,
    LXW_ERROR_SHEETNAME_START_END_APOSTROPHE, LXW_ERROR_SHEETNAME_ALREADY_USED,
    LXW_ERROR_32_STRING_LENGTH_EXCEEDED, LXW_ERROR_128_STRING_LENGTH_EXCEEDED,
    LXW_ERROR_255_STRING_LENGTH_EXCEEDED, LXW_ERROR_MAX_STRING_LENGTH_EXCEEDED,
    LXW_ERROR_SHARED_STRING_INDEX_NOT_FOUND,
    LXW_ERROR_WORKSHEET_INDEX_OUT_OF_RANGE,
    LXW_ERROR_WORKSHEET_MAX_URL_LENGTH_EXCEEDED,
    LXW_ERROR_WORKSHEET_MAX_NUMBER_URLS_EXCEEDED, LXW_ERROR_IMAGE_DIMENSIONS,
    LXW_MAX_ERRNO
]#